# Initialize Bitbucket Server PostgreSQL database
gosu postgres postgres --single <<- EOSQL
	CREATE ROLE $BITBUCKET_DB_USER WITH LOGIN PASSWORD '$BITBUCKET_DB_PASS' VALID UNTIL 'infinity';
	CREATE DATABASE $BITBUCKET_DB_NAME WITH ENCODING='UTF8' OWNER=$BITBUCKET_DB_USER CONNECTION LIMIT=-1;
EOSQL
