# Initialize Stash PostgreSQL database
gosu postgres postgres --single <<- EOSQL
	CREATE ROLE $STASH_DB_USER WITH LOGIN PASSWORD '$STASH_DB_PASS' VALID UNTIL 'infinity';
	CREATE DATABASE $STASH_DB_NAME WITH ENCODING='UTF8' OWNER=$STASH_DB_USER CONNECTION LIMIT=-1;
EOSQL
